- name: Prometheus configuration
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server

- name: Node Exporter Configuration
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter