- name: Install Maven
  ansible.builtin.yum:
    name: maven

- name: Include app_prereq_setup
  ansible.builtin.import_tasks:
    file: app-prereq-setup.yml

- name: Download dependencies & package
  ansible.builtin.shell: mvn clean package; mv target/{{component}}-1.0.jar {{component}}.jar
  args:
    chdir: /app

- name: Schema Setup
  ansible.builtin.import_tasks:
    file: schema-setup.yml
  when: schema_type is defined

- name: SystemD Setup
  ansible.builtin.import_tasks:
    file: systemd-setup.yml

