#print_head "Copy systemd Service file"
#cp ${code_dir}/configs/${component}.service /etc/systemd/system/${component}.service &>>${log_file}
#status_check $?
#
#sed -i -e "s/ROBOSHOP_USER_PASSWORD/${roboshop_app_password}/" /etc/systemd/system/${component}.service &>>${log_file}
#echo ${roboshop_app_password}
#print_head "Reload SystemD"
#systemctl daemon-reload &>>${log_file}
#status_check $?
#print_head "Enable ${component} service "
#systemctl enable ${component} &>>${log_file}
#status_check $?
#print_head "Restart ${component} service"
#systemctl restart ${component} &>>${log_file}
#status_check $?
#
#}

