groups:
  - name: Roboshop-Service Alerts
    rules:
    {% for component in components %}

    - alert: Service Down Alerts - {{ component.name }} service
      expr: node_systemd_unit_state{exported_name="{{ component.service_name }}.service", state="active"}
      for: 30s
      labels:
        severity: critical
        appName: {{ component.name }}
      annotations:
          summary: Service Down on some Server - Service name - {{ component.service_name }}.service
    {% endfor %}